apiVersion: v2
name: test-deps
description: A demo dependencies Helm chart for testing the release process
type: application
version: 1.0.0
dependencies:
  - name: test-dependency
    version: "1.0.0"
    repository: "https://example.com/charts"
    condition: dependency.enabled
